src/datasplash/api.clj
src/datasplash/bq.clj
src/datasplash/core.clj

Wrapper to use FixedWindows and Sessions, and adding a custom trigger.
Adding a trigger makes it necessary to set with-allowed-lateness. In that case, should the schema be {:trigger {:trigger t :with-allowed-lateness d :accumulate-mode m}} ?

Adding windowing support

---

src/clj/datasplash/core.clj
test/datasplash/api_test.clj

This correct fixed window docstring and adds tests

Applying my commits in master

---

src/clj/datasplash/core.clj
src/clj/datasplash/pubsub.clj
test/datasplash/api_test.clj

Retrieve the timestamp in an attribute of the message with an optional :timestamp-label keyword
```clojure
(ps/read-from-pubsub subscription {:kind :subscription :timestamp-label "timestamp"} pipeline)
```

Pubsub with custom timestamp

---

src/clj/datasplash/core.clj

Just for information, not tested yet.

Added compression for textio write

---

src/clj/datasplash/core.clj

Try macro that wraps the body in a safe-exec.

added ptry macro to simplify try/catch code

---

src/clj/datasplash/bq.clj

- Fixing return types: https://dev.clojure.org/jira/browse/CLJ-1232?focusedCommentId=34819&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-34819
To test this:
```
(set! *warn-on-reflection* true)
(.set (bq/->schema {}) "a" "e")
```
should not raise a Reflection warning.
- removing `proxy` usage for clojure 1.9.0.
I would like someone to double check this. I did test it on a simple pipeline but I may have missed something.

Fix return type and removed proxies. Need review

---

src/clj/datasplash/core.clj
test/datasplash/api_test.clj

Nobody remembers the order of the arguments. I often add a comment above each one to remember myself which is which. A map argument solves this problem.

combine-fn: accept a map to clarify the arguments

---

src/clj/datasplash/core.clj

fix write-text-file without file-format

---

src/clj/datasplash/datastore.clj

I have tested this and it works. It's a simple addition, but hopefully it helps someone else.

feature: Add delete-datastore-raw to datastore features

---

src/clj/datasplash/examples.clj

An attempt to fix https://github.com/ngrunwald/datasplash/issues/73 but I could not make the `defoptions` macro work correctly so I had to use a different option name for the Pub/Sub project.

Fix kinglear URL and pubsub example

---

README.md

Spent a couple of hours trying to figure out #79.  Thought adding an additional caveat in the Readme would be useful. Thanks!

add caveat about having classes dir for compile to work

---

src/clj/datasplash/core.clj

This fix is justifies by the following [comment](https://ask.clojure.org/index.php/9893/require-is-not-thread-safe?show=9902#c9902)

safe-exec-cfg to participate in clojure's REQUIRE_LOCK #97

---

project.clj
src/clj/datasplash/bq.clj
src/clj/datasplash/core.clj
src/clj/datasplash/es.clj
test/datasplash/api_test.clj

I had to modify some of the examples due to small differences between cheshire and jsonista, but all tests are passing with these changes.

swap cheshire for jsonista

---

CHANGELOG.md
project.clj
src/clj/datasplash/bq.clj
src/clj/datasplash/core.clj
src/clj/datasplash/es.clj
test/datasplash/api_test.clj

Switch broke several pipelines. Will retry switch away from Cheshire to charred in an upcoming release.

revert jsonista

---

CHANGELOG.md
src/clj/datasplash/api.clj

Resolves https://github.com/ngrunwald/datasplash/issues/94

don't require bq, pubsub, datastore in api.clj

---

project.clj
src/clj/datasplash/bq.clj
src/clj/datasplash/core.clj
src/clj/datasplash/es.clj
test/datasplash/api_test.clj

Charred has zero external dependencies, but still offers the same performance as jsonista. I hope it also resolves your issue @edporras. The tests are all passing on this version.

Switch from Cheshire to Charred

---

CHANGELOG.md
src/clj/datasplash/core.clj
src/java/AbstractClojureDoFn.java

Hi @edporras The last PR might not have worked.  Retrying. Thank-you.

Version v0.7.8, complete dofn lifecycle

---

project.clj
src/clj/datasplash/bq.clj
src/clj/datasplash/core.clj
src/clj/datasplash/es.clj

Rebase cheshire->charred on new branch

---

project.clj

Bumping Charred to include the fix from Chris for conversion of clojure set to a json array.

bump charred

---

src/clj/datasplash/bq.clj

Tested on a basic pipeline, I can show you the result.
Example code : 
```
(defn -main
[]
(let [pipeline (ds/make-pipeline pipeline-options)
data (ds/generate-input
[{"d" "2021-01-01 00:00:00" "c" 1} {"d" "2022-01-01 00:00:00" "c" 2}]
pipeline)]
(datasplash.bq/write-bq-table
"project:dataset.table"
{:schema [{:name "d" , :type "TIMESTAMP"}
{:name "c" , :type "INTEGER"}]
:create-disposition :if-needed
:write-disposition :truncate
:with-optimized-writes true
:time-partitioning {:type :month
:field "d"}
:clustering ["c"]}
data)
(ds/run-pipeline pipeline)))
```

Added BQ clustering + optimized writes options in bq-write-table +  use clean-name in clustering/partitioning

---

src/clj/datasplash/core.clj
test/datasplash/core_test.clj

handle collection for generating pipeline args

---

src/clj/datasplash/bq.clj

Hello,
I added a small option in read-bq-raw. This allows to manually select query location in bigquery.
Thanks

Add withQueryLocation => :query-location option in bq/read-bq-raw

---

README.md

Unless I’m missing something, I don’t think these are necessary.

README: remove unused imports in example code

---

src/clj/datasplash/core.clj

Hello,
A small PR to fix some clj-kondo warnings.
Biggest changes are lines: 84 and 1982
Regards

chore: fix some kondo warnings

---

README.md
project.clj
src/clj/datasplash/bq.clj
src/clj/datasplash/core.clj
src/clj/datasplash/datastore.clj
src/clj/datasplash/es.clj
src/clj/datasplash/examples.clj
src/clj/datasplash/kafka.clj
src/clj/datasplash/pubsub.clj

Hi,
Here is a PR to address issue #146.
Regards,
Kawas

Remove main entry

---

CHANGELOG.md
project.clj
src/clj/datasplash/bq.clj

and clojure to 1.11.3
Holding off on nippy for now

bump beam to 2.56.0
