ngrunwald/datasplash

src/datasplash/core.clj

The current code performs a test at each loop iteration. This PR moves the test out of the loop (no pun intended). I don’t have any data on the performance improvement, thought.
I wasn’t able to run `lein test` because of an exception:
```
$ lein test
Retrieving org/hamcrest/hamcrest-all/1.3/hamcrest-all-1.3.pom from central
Retrieving org/hamcrest/hamcrest-all/1.3/hamcrest-all-1.3.jar from central
Compiling datasplash.api-test
Compiling datasplash.examples
Compiling clj-time.core
Exception in thread "main" java.lang.NoClassDefFoundError: clojure/tools/logging/impl/LoggerFactory, compiling:(/tmp/form-init1405529213507449495.clj:1:73)
at clojure.lang.Compiler.load(Compiler.java:7391)
```

read-json-file: move a test out of the loop

---

.gitignore
project.clj
src/datasplash/core.clj

I ran into problems with slf4j when using datasplash as a dependency because I wanted to use logback as the implenmentation, but I solved this by moving the slf4j dependencies into the :dev profile.
Could this be something you're willing to make change? I notice you have added the comment 
`;; exclude these if you want something else` to `project.clj`, but that won't work for those using datasplash as a dependency.

Move sl4j deps to dev

---

project.clj
src/datasplash/examples.clj
src/datasplash/pubsub.clj

This pull request adds PubsubIO source and sinks to datasplash. As the datasplash `apply-transform` handles wrapping a PCollection elegantly and is well tested, there is no tests. Also due to the existing functionality, the commit is very small, as it took very little to get PubsubIO working. It is difficult to test this locally, as it Pubsub streaming jobs must be run on the Dataflow Service. I have added a (commented out) working example with the corresponding image from the Dataflow Dashboard.

Add pubsub io

---

src/datasplash/api.clj
src/datasplash/core.clj
test/datasplash/api_test.clj

Also:
- fixed (and tested) ds/with-timestamp function (now we know it works thanks to the sessions-window test)
- added fixed windows
Missing:
- complete test for fixed and sliding windows, for now it's just a test to see if the pipeline run, but not on the results.

Tests for windows bindings

---

src/clj/datasplash/bq.clj
test/datasplash/bq_test.clj

Simple extension to reference day partitions with BigQuery outputs

Added support for time partitioned big query tables

---

src/clj/datasplash/core.clj

`ds/val` does not coerce to clojure datastructure, which can lead to strange error since some dataflow Iterator objects are unfreezable by nippy.

val coerce to clojure value

---

src/clj/datasplash/core.clj
src/clj/datasplash/datastore.clj

This pull request adds a switch on collection emptiness in generate-input to make the function support empty Pcollections generation.
Indeed, the method Create/of does not accept empty collections since it cannot guess which coder to use, so that `(ds/generate-input [] {:name "my-transform"} pipeline)` throws an Exception.
Instead, we must use Create/empty with a coder as argument (here a nippy coder), which is done there.
This feature can be useful for pipeline automation when you do not want to read data everytime (at certain hours for instance) and thus to do not break the pipeline with nil you would have to check everywhere.

Make generate-input support empty collections

---

src/clj/datasplash/pubsub.clj

The `write-to-pubsub` docstring had a mistake in it. And the `:type` option was poorly explained.
Next step would be to add the `:json` type that automatically parse/encode the messages and the `encode-messages` and `decode-messages` functions should support 1-arity call.

Corrected and improved pubsub docstrings

---

src/clj/datasplash/api.clj
src/clj/datasplash/core.clj

**Additions description**
Add the following transforms to datasplash :
- read-text-files
- read-edn-files
- read-json-files
mirroring singular versions.
These transforms take a PCollection of uris/paths (String) as input and spawn a single PTransform in the graph. 
**Covered use case**
In some cases, the user has to read from a large number of files but without the possibility to create a single pattern for it, which is the case when a datasource is separated into many daily folders.
In that case, we have two possibilities:
- match all folders, then filter read data, which can be overkill and very costly when you need only a smaller subset of the data
- spawn a read transform for every file, which can cause an exception because the graph is too large (like if you want to read from 250 …

Add read-x-files transforms

---

project.clj
src/clj/datasplash/es.clj
src/java/ExtractKeyFn.java

- settings and mappings need to be sent before writing
- write works better with multicore workers and a bigger `max-batch-size-bytes`

add ElasticsearchIO wrapper

---

src/clj/datasplash/core.clj

Small fix to :many-files option adding a second arity to its :action keyword. Indeed, the resolution failed since with-opts passes two arguments to it.

Fix :many-files option in read-text-file

---

src/clj/datasplash/core.clj

Each of these methods declares a modified `opts` local but that doesn't seem to be used in the body (instead using the original `options` from the pipeline). I'm not sure if the `let` is a leftover from something else or not.

Use correct opts in read-edn*, read-text*, and read-json* fns

---

CHANGELOG.md
project.clj
src/clj/datasplash/core.clj

As suggested by Nippy's author. See
https://github.com/ptaoussanis/nippy

Bump nippy version to 3.1.1

---

src/clj/datasplash/core.clj
src/clj/datasplash/es.clj
test/datasplash/api_test.clj

I remembered that I had strange serialization issues like this before when using the `#()` notation, so I have fixed the issue by wrapping the function like this:
```
with-key-fn (fn [val] (json/read-value val (json/object-mapper {:decode-key-fn key-fn})))
```
The tests no longer through with this solution.

fix: serialization errors on jsonista

---

src/clj/datasplash/api.clj
src/clj/datasplash/core.clj
test/datasplash/api_test.clj

This adds three new `set` operations to the API. `intersect-distinct`, `union-distinct` and `except-distinct`.

Add Set distinct operations for PCollections

---

src/clj/datasplash/core.clj
test/datasplash/api_test.clj

This makes it backwards compatible with `cheshire` which will not throw on empty lines. As discussed doesn't yet deal with combinatorial explosion of `charred` opts.

Don't throw on empty lines.

---

project.clj
src/clj/datasplash/core.clj

Charred now supports the 1.11 options map passing syntax.

Bump charred + use 1.11 options map passing syntax

---

README.md

Unless I’m missing something this can’t work as-is:
> Syntax error compiling at (/tmp/form-init13710778033494800017.clj:1:1).
> Unable to resolve symbol: compile in this context

README: fix example code

---

src/clj/datasplash/api.clj
src/clj/datasplash/core.clj
test/datasplash/api_test.clj

Hello,
Here is a pull request to add a `distinct-by` function.
**N.B :** This PR has 2 commits only to show off two different implementations.
- The first implementation makes use of the Java API but exposes class details.
- The second implementation is more *Datasplash idiomatic*
After PR review, I'll keep only one implementation.
Regards

Add distinct-by

---

src/clj/datasplash/api.clj
src/clj/datasplash/core.clj
test/datasplash/api_test.clj

Looking at our codebase, I can see a lot of `(d/map ...)` followed by `(d/filter some? ...)`. Its seems that a `keep` ptransform may be useful.
Beware the `dkeep` implementation only discards null values.

Add a keep ptransform

---

src/clj/datasplash/bq.clj
test/datasplash/bq_schema_test.clj

* added more tests to bq ns
* now normalizing bq table schema mode to allow us to use `:required`, `:record`, `:nullable`
* define specs to validate table schema values for mode & type, and time-partitioning types as per BQ docs
* add initial support for setMaxLength, setPrecision, setScale
* general cleanup, etc

bq clean up and normalize mode type

---

project.clj
resources/clj-kondo.exports/datasplash/datasplash/config.edn
src/clj/datasplash/testing.clj
src/clj/datasplash/testing/assert.clj
src/java/PredicateMatcher.java
test/datasplash/api_test.clj
test/datasplash/testing/assert_test.clj

Hello,
Here is a PR to add a namespace to expose test helpers wrapping `PAssert`.
Pro:
- Writing test is shorter
- We can coerce a pcoll to various shape before testing: Iterable, Map, Mutimap, Singleton obj
- Writing test, we can see what is inside a pcoll at runtime with a matcher like `(dt/satisfies tap>)`
Cons:
- `PAssert` raises `AssertionError` and gives only a text message about what went wrong
A complete rewrite of `test_api.clj` to use those new helpers. We reduced the file size by a third and tests run a little bit faster.
The project has a clj-kondo config for developers, but it seems that this file is more a personal configuration file for whoever uses clj-kondo. Do we want to keep it or let developers do as they please?
Regards

Add test helpers

---

src/clj/datasplash/core.clj

by not instantiating the parser for every object, but creating it once per worker

improve json parsing speed

---

CHANGELOG.md
src/clj/datasplash/bq.clj
test/datasplash/bq_test.clj

* enable set collation for string types
* add json and range types to spec for schema validation
* split table-field spec defs by type

updates to BQ ns : new schema types, support for set collation

---

CHANGELOG.md
project.clj

As per
https://raw.githubusercontent.com/apache/beam/v2.59.0/buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy beam uses kafka 2.4.1 so downgrading kafka-clients to match.

build: bump to beam 2.59.0

---

src/clj/datasplash/bq.clj

These options allow us to define where Dataflow will write temporary BigQuery table during its processing instead of letting it create a lot of temporary datasets (which also requires elevated rights).

Add temp-dataset and temp-project options in BQ read

---

CHANGELOG.md
src/clj/datasplash/es.clj

Fix bug when using id-fn, index-fn, type-fn options

Fix: bug on ES writing with fn options

---

CHANGELOG.md
project.clj
src/clj/datasplash/kafka.clj

* Bump beam to 2.64.0.
* Bump slf4j to 2.x.
* Bump charred to 1.037.
* Bump nippy to 3.5.0.

bump beam to 2.64.0, other deps
